### PR TITLE
Wastelands of Baedoor compatibility (1.16, but can be also for 1.14, 1.15, 1.17, even 1.12)

### PR DESCRIPTION
**Pull request by Toma400**
So this is PR you asked me on CF. Explaining details: my mod uses "firearm experience" which counts progression of using various guns (it's used to improve their performance over time)

> if that does not mean adding a ton of lines of code

Definitely not! The only thing you need to implement is setting score for scoreboard called "gun_experience". After each successful shot it should raise by 1. Of course you can also use that scoreboard yourself, if you would like to implement some mechanics.
If you would like to see if it works, you can download [mod's file](https://www.curseforge.com/minecraft/mc-mods/wastelands-of-baedoor). While in-game, command "wobrCheck_Experience" shows experience for firearms.

This can be implemented for versions 1.15-1.16 (actually supported), but as 1.12, 1.14 and 1.17 will soon receive similar support, it can be implemented for these versions as well. Forge API, of course.

PS I'm sorry if I messed something up, I'm still so new on GitHub ;-;

### CODE REVIEW

**Comment by ewewukek** [comment]
there is definitely something wrong with this PR ;)
regular flow is following: 1. create a fork, 2. make changes in your fork, 3. create a request to pull changes from your fork to upstream.

I'll implement "gun_experience" score and port it to 1.17 - 1.14 (oldest musketmod version)

**Comment by Toma400** [comment]
I knew it that there's something related to code! ;_; sorry once again for that, I really need to start working on GitHub to get to know its basic stuff.

Thanks for such broad implementation tho! I really like how vanilla and close to my main inspiration (Balkon's Mod) Musketmod is. Will be great to see it compatibile ^^

**Comment by ewewukek** [comment]
I'd like to avoid adding score objective if wobr is not installed. my concern that it could be created with parameters different from wobr. is it ok if I increase gun_experience only if it already exists? your mod could create it upon entering world (setting it to itself will probably do that)

**Comment by Toma400** [comment]
That's totally okay, of course! Although it would work - as I imagine - as "storage" for the past experience, so this wouldn't be an issue per se (some could say it's even a feature :P), but I see what's the issue, and it would probably make more sense to make it conditional.

**Comment by ewewukek** [comment]
after some studying I decided that it's safe to create score in musketmod. my concern was baseless)

let me know if some compatibility issues will ever occur in the future

**Comment by Toma400** [comment]
Of course! For now it works perfectly on 1.15, I will test 1.16 soon too. Thank you so much, glad to have your mod compatibile ^^

I will make dedicated "compatibility button" for our compatibility to be shown on my page too; let me know if you have any preferred images to be chosen (if not, then I will try to make representative screenshot myself in free time).

**Pull request closed without merging**
